import type { TerraformMultiRegionInput } from '../types';
import { regionToSlug } from '../utils';

export function generateMainTf(input: TerraformMultiRegionInput): string {
  const lines: string[] = [];

  lines.push(`# --------------------------------------------------------------------------`);
  lines.push(`# Root module — Multi-region Classic-to-VPC migration`);
  lines.push(`# Generated by IBM Cloud Infrastructure Explorer`);
  lines.push(`# --------------------------------------------------------------------------`);
  lines.push('');
  lines.push(`data "ibm_resource_group" "group" {`);
  lines.push(`  name = var.resource_group_name`);
  lines.push(`}`);
  lines.push('');

  // Per-region module calls
  for (const region of input.regions) {
    const slug = regionToSlug(region);
    const hclKey = `"${region}"`;

    lines.push(`# --- ${region} ---`);
    lines.push('');

    // VPC module
    lines.push(`module "vpc_${slug}" {`);
    lines.push(`  source    = "./modules/vpc"`);
    lines.push(`  providers = { ibm = ibm.${slug} }`);
    lines.push('');
    lines.push(`  vpc_name                   = var.vpcs[${hclKey}].name`);
    lines.push(`  resource_group_id          = data.ibm_resource_group.group.id`);
    lines.push(`  default_sg_name            = var.vpcs[${hclKey}].default_sg_name`);
    lines.push(`  default_acl_name           = var.vpcs[${hclKey}].default_acl_name`);
    lines.push(`  default_routing_table_name = var.vpcs[${hclKey}].default_routing_table_name`);
    lines.push(`  migration_subnet_cidr      = var.vpcs[${hclKey}].migration_subnet_cidr`);
    lines.push(`  migration_subnet_zone      = var.vpcs[${hclKey}].migration_subnet_zone`);
    lines.push(`  tags                       = var.tags`);
    lines.push(`}`);
    lines.push('');

    // Subnets module
    lines.push(`module "subnets_${slug}" {`);
    lines.push(`  source    = "./modules/subnets"`);
    lines.push(`  providers = { ibm = ibm.${slug} }`);
    lines.push('');
    lines.push(`  vpc_id            = module.vpc_${slug}.vpc_id`);
    lines.push(`  resource_group_id = data.ibm_resource_group.group.id`);
    lines.push(`  subnets           = var.vpcs[${hclKey}].subnets`);
    lines.push(`  tags              = var.tags`);
    lines.push(`}`);
    lines.push('');

    // Security groups module
    lines.push(`module "security_groups_${slug}" {`);
    lines.push(`  source    = "./modules/security_groups"`);
    lines.push(`  providers = { ibm = ibm.${slug} }`);
    lines.push('');
    lines.push(`  vpc_id            = module.vpc_${slug}.vpc_id`);
    lines.push(`  resource_group_id = data.ibm_resource_group.group.id`);
    lines.push(`  security_groups   = var.vpcs[${hclKey}].security_groups`);
    lines.push(`  tags              = var.tags`);
    lines.push(`}`);
    lines.push('');

    // Network ACLs module
    lines.push(`module "network_acls_${slug}" {`);
    lines.push(`  source    = "./modules/network_acls"`);
    lines.push(`  providers = { ibm = ibm.${slug} }`);
    lines.push('');
    lines.push(`  vpc_id            = module.vpc_${slug}.vpc_id`);
    lines.push(`  resource_group_id = data.ibm_resource_group.group.id`);
    lines.push(`  acl_name          = var.vpcs[${hclKey}].acl_name`);
    lines.push(`  tags              = var.tags`);
    lines.push(`}`);
    lines.push('');
  }

  // Transit Gateway (only when 2+ regions)
  if (input.transitGateway) {
    lines.push(`# --- Transit Gateway ---`);
    lines.push('');
    lines.push(`module "transit_gateway" {`);
    lines.push(`  source = "./modules/transit_gateway"`);
    lines.push('');
    lines.push(`  tgw_name          = var.tgw_name`);
    lines.push(`  tgw_location      = var.tgw_location`);
    lines.push(`  resource_group_id = data.ibm_resource_group.group.id`);
    lines.push('');

    // vpc_connections map
    lines.push(`  vpc_connections = {`);
    for (const region of input.regions) {
      const slug = regionToSlug(region);
      lines.push(`    "${region}" = {`);
      lines.push(`      vpc_crn = module.vpc_${slug}.vpc_crn`);
      lines.push(`      name    = "tgw-conn-${region}"`);
      lines.push(`    }`);
    }
    lines.push(`  }`);
    lines.push('');

    // migration_subnet_cidrs list
    lines.push(`  migration_subnet_cidrs = [`);
    for (const region of input.regions) {
      lines.push(`    var.vpcs["${region}"].migration_subnet_cidr,`);
    }
    lines.push(`  ]`);
    lines.push('');
    lines.push(`  tags = var.tags`);
    lines.push(`}`);
    lines.push('');
  }

  return lines.join('\n');
}
