import type { TerraformMultiRegionInput } from '../types';

export function generateReadme(input: TerraformMultiRegionInput): string {
  const regionCount = input.regions.length;
  const totalSubnets = input.regions.reduce(
    (sum, r) => sum + Object.keys(input.vpcs[r].subnets).length, 0);
  const totalSGs = input.regions.reduce(
    (sum, r) => sum + Object.keys(input.vpcs[r].securityGroups).length, 0);
  const hasTGW = !!input.transitGateway;

  const regionList = input.regions.map((r) => `\`${r}\``).join(', ');

  let resourceTable = `| Resource | Count | Terraform Resource |
|----------|-------|--------------------|
| VPCs | ${regionCount} | \`ibm_is_vpc\` |
| Address Prefixes | ${totalSubnets + regionCount} | \`ibm_is_vpc_address_prefix\` |
| Subnets (application) | ${totalSubnets} | \`ibm_is_subnet\` |
| Migration Subnets | ${regionCount} | \`ibm_is_subnet\` |
| Security Groups | ${totalSGs} | \`ibm_is_security_group\` |
| Security Group Rules | varies | \`ibm_is_security_group_rule\` |
| Network ACLs | ${regionCount} | \`ibm_is_network_acl\` |`;

  if (hasTGW) {
    resourceTable += `
| Transit Gateway | 1 | \`ibm_tg_gateway\` |
| TGW VPC Connections | ${regionCount} | \`ibm_tg_connection\` |
| TGW Classic Connection | 1 | \`ibm_tg_connection\` |
| TGW Prefix Filters | ${regionCount + 1} | \`ibm_tg_connection_prefix_filter\` |`;
  }

  let tgwSection = '';
  if (hasTGW) {
    tgwSection = `
## Transit Gateway

A global Transit Gateway connects all ${regionCount} VPCs and the Classic
infrastructure network. Prefix filters on the Classic connection **permit only
the migration subnet CIDRs** (172.16.x.0/24) and deny everything else.

This allows controlled connectivity between Classic and VPC during migration
without exposing the entire Classic network to VPC.
`;
  }

  return `# Multi-Region VPC Migration — Terraform Configuration

> Auto-generated by **IBM Cloud Infrastructure Explorer**

This Terraform configuration creates a multi-region VPC architecture from your
Classic infrastructure. One VPC is created per region (${regionList}), with
subnets mapped from Classic VLANs, security groups replicated where their
bound servers exist, and a migration subnet in each VPC for Classic connectivity.

## What Gets Created

${resourceTable}

## Architecture

\`\`\`
${input.regions.map((r) => `${r}: VPC + subnets + SGs + migration subnet`).join('\n')}${hasTGW ? `
Transit Gateway: connects all VPCs + Classic infrastructure
  └─ Prefix filters: PERMIT migration CIDRs only` : ''}
\`\`\`

## Prerequisites

- Terraform >= 1.5 (or IBM Cloud Schematics)
- IBM Cloud API key with VPC Infrastructure permissions
- Target resource group must already exist

## Quick Start — IBM Cloud Schematics

1. Upload this zip to a **Schematics workspace**
   - IBM Cloud Console → Schematics → Workspaces → Create
   - Upload the \`.tar.gz\` or point to a Git repo containing these files
2. Set the \`ibmcloud_api_key\` variable in the workspace settings
3. Review \`terraform.tfvars\` and adjust values as needed
4. Click **Generate plan** to preview changes
5. Click **Apply plan** to create resources

## Quick Start — Local Terraform

\`\`\`bash
export IC_API_KEY="your-ibm-cloud-api-key"
terraform init
terraform plan
terraform apply
\`\`\`

## Customisation

Edit \`terraform.tfvars\` to:

- **Add/remove VPCs** — edit the \`vpcs\` map (one entry per region)
- **Change VPC names** — update the \`name\` field within each region
- **Add/remove subnets** — edit the \`subnets\` map within each region
- **Modify security group rules** — edit the \`security_groups\` map per region
- **Change resource group** — update \`resource_group_name\`
- **Adjust migration subnets** — change \`migration_subnet_cidr\` per region

## Migration Subnets

Each VPC includes a dedicated migration subnet (172.16.x.0/24) in zone 1.
These subnets are reachable from Classic infrastructure${hasTGW ? ' via the Transit Gateway' : ''} and
provide a landing zone for migrating workloads.

| Region | Migration Subnet |
|--------|-----------------|
${input.regions.map((r) => `| ${r} | ${input.vpcs[r].migrationSubnetCidr} |`).join('\n')}
${tgwSection}
## Security Group Placement

Security groups are placed in each VPC where their bound Classic servers exist
(inferred from Classic relationship data). Security groups with no server
bindings are replicated to all VPCs.

## Subnet Mapping

Subnets were mapped from Classic VLANs to VPC zones based on datacenter-to-region
mapping. Review the CIDR ranges in \`terraform.tfvars\` to ensure they don't
conflict with existing VPC address ranges.

## Security Group Rules

Classic security group rules were translated:
- \`ingress\` → \`inbound\`, \`egress\` → \`outbound\`
- \`remoteIp\` → \`remote\` CIDR
- Rules without a protocol are treated as "allow all traffic"

Review rules carefully — some Classic constructs (e.g., remote group
references) may need manual adjustment.

## Network ACLs

A default "allow all" network ACL is created per VPC. Customise the rules in
\`modules/network_acls/main.tf\` as needed for your security requirements.

## Files

| File | Purpose |
|------|---------|
| \`main.tf\` | Root module — per-region module calls${hasTGW ? ' + Transit Gateway' : ''} |
| \`variables.tf\` | Input variable declarations |
| \`terraform.tfvars\` | Pre-populated values — **edit this** |
| \`outputs.tf\` | Output values (VPC IDs, subnet IDs, etc.) |
| \`versions.tf\` | Terraform and provider version constraints |
| \`provider.tf\` | IBM Cloud provider aliases (one per region) |
| \`modules/vpc/\` | VPC + migration subnet |
| \`modules/subnets/\` | Address prefixes and subnets |
| \`modules/security_groups/\` | Security groups and rules |
| \`modules/network_acls/\` | Network ACL with default rules |${hasTGW ? '\n| `modules/transit_gateway/` | Transit Gateway + connections + prefix filters |' : ''}
`;
}
