import { Paragraph, TextRun, BorderStyle } from 'docx';
import { PURPLE, DARK } from './styles';

export function aiDisclaimer(): Paragraph {
  return new Paragraph({
    spacing: { before: 120, after: 120 },
    children: [
      new TextRun({
        text: 'This section was generated by AI (IBM watsonx.ai) and should be reviewed for accuracy.',
        italics: true,
        color: PURPLE,
        size: 18,
      }),
    ],
  });
}

export function aiNarrativeSection(narrative: string): Paragraph[] {
  const paragraphs: Paragraph[] = [aiDisclaimer()];

  const lines = narrative.split('\n').filter((l) => l.trim().length > 0);
  for (const line of lines) {
    paragraphs.push(
      new Paragraph({
        spacing: { after: 80 },
        border: {
          left: { style: BorderStyle.SINGLE, size: 6, color: PURPLE, space: 8 },
        },
        indent: { left: 200 },
        children: [
          new TextRun({
            text: line.trim(),
            size: 22,
            color: DARK,
          }),
        ],
      }),
    );
  }

  return paragraphs;
}
