import type { ColumnDefinition } from './resources';

export type VpcResourceCategory = 'VPC Compute' | 'VPC Network' | 'VPC Storage' | 'VPC Security' | 'VPC Other';

export interface VpcResourceType {
  key: string;
  label: string;
  category: VpcResourceCategory;
  worksheetName: string;
  columns: ColumnDefinition[];
}

export const VPC_RESOURCE_TYPES: VpcResourceType[] = [
  // ── Compute ─────────────────────────────────────────────────────
  {
    key: 'vpcInstances',
    label: 'Virtual Server Instances',
    category: 'VPC Compute',
    worksheetName: 'vVpcInstances',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'status', header: 'Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'profile', header: 'Profile', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'vcpu', header: 'vCPUs', dataType: 'number', defaultVisible: true, sortable: true },
      { field: 'memory', header: 'Memory (GB)', dataType: 'number', defaultVisible: true, sortable: true },
      { field: 'zone', header: 'Zone', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'vpcName', header: 'VPC', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'primaryIp', header: 'Primary IP', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
      { field: 'resourceGroup', header: 'Resource Group', dataType: 'string', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'vpcBareMetalServers',
    label: 'Bare Metal Servers',
    category: 'VPC Compute',
    worksheetName: 'vVpcBareMetal',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'status', header: 'Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'profile', header: 'Profile', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'zone', header: 'Zone', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'vpcName', header: 'VPC', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
      { field: 'resourceGroup', header: 'Resource Group', dataType: 'string', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'vpcDedicatedHosts',
    label: 'Dedicated Hosts',
    category: 'VPC Compute',
    worksheetName: 'vVpcDedicatedHosts',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'state', header: 'State', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'profile', header: 'Profile', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'zone', header: 'Zone', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'vcpu', header: 'vCPUs', dataType: 'number', defaultVisible: true, sortable: true },
      { field: 'memory', header: 'Memory (GB)', dataType: 'number', defaultVisible: true, sortable: true },
      { field: 'instanceCount', header: 'Instances', dataType: 'number', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'vpcPlacementGroups',
    label: 'Placement Groups',
    category: 'VPC Compute',
    worksheetName: 'vVpcPlacementGroups',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'strategy', header: 'Strategy', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: true, sortable: true },
      { field: 'resourceGroup', header: 'Resource Group', dataType: 'string', defaultVisible: false, sortable: true },
    ],
  },

  // ── Network ─────────────────────────────────────────────────────
  {
    key: 'vpcs',
    label: 'VPCs',
    category: 'VPC Network',
    worksheetName: 'vVpcs',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'status', header: 'Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'classicAccess', header: 'Classic Access', dataType: 'boolean', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: true, sortable: true },
      { field: 'resourceGroup', header: 'Resource Group', dataType: 'string', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'vpcSubnets',
    label: 'Subnets',
    category: 'VPC Network',
    worksheetName: 'vVpcSubnets',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'status', header: 'Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'cidr', header: 'CIDR', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'availableIps', header: 'Available IPs', dataType: 'number', defaultVisible: true, sortable: true },
      { field: 'totalIps', header: 'Total IPs', dataType: 'number', defaultVisible: true, sortable: true },
      { field: 'zone', header: 'Zone', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'vpcName', header: 'VPC', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'vpcSecurityGroups',
    label: 'Security Groups',
    category: 'VPC Network',
    worksheetName: 'vVpcSecurityGroups',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'vpcName', header: 'VPC', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'ruleCount', header: 'Rules', dataType: 'number', defaultVisible: true, sortable: true },
      { field: 'targetCount', header: 'Targets', dataType: 'number', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'vpcFloatingIps',
    label: 'Floating IPs',
    category: 'VPC Network',
    worksheetName: 'vVpcFloatingIps',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'address', header: 'Address', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'status', header: 'Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'target', header: 'Target', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'zone', header: 'Zone', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'vpcPublicGateways',
    label: 'Public Gateways',
    category: 'VPC Network',
    worksheetName: 'vVpcPublicGateways',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'status', header: 'Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'vpcName', header: 'VPC', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'floatingIp', header: 'Floating IP', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'zone', header: 'Zone', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'vpcNetworkAcls',
    label: 'Network ACLs',
    category: 'VPC Network',
    worksheetName: 'vVpcNetworkAcls',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'vpcName', header: 'VPC', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'ruleCount', header: 'Rules', dataType: 'number', defaultVisible: true, sortable: true },
      { field: 'subnetCount', header: 'Subnets', dataType: 'number', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'vpcLoadBalancers',
    label: 'Load Balancers',
    category: 'VPC Network',
    worksheetName: 'vVpcLoadBalancers',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'hostname', header: 'Hostname', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'isPublic', header: 'Public', dataType: 'boolean', defaultVisible: true, sortable: true },
      { field: 'operatingStatus', header: 'Operating Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'provisioningStatus', header: 'Provisioning Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'vpcVpnGateways',
    label: 'VPN Gateways',
    category: 'VPC Network',
    worksheetName: 'vVpcVpnGateways',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'status', header: 'Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'mode', header: 'Mode', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'subnet', header: 'Subnet', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'transitGateways',
    label: 'Transit Gateways',
    category: 'VPC Network',
    worksheetName: 'vTransitGateways',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'status', header: 'Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'location', header: 'Location', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'routingScope', header: 'Routing Scope', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'resourceGroup', header: 'Resource Group', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'transitGatewayConnections',
    label: 'Transit Gateway Connections',
    category: 'VPC Network',
    worksheetName: 'vTGConnections',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'status', header: 'Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'networkType', header: 'Network Type', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'transitGatewayName', header: 'Transit Gateway', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'networkId', header: 'Network ID', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'ownershipType', header: 'Ownership', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'directLinkGateways',
    label: 'Direct Link Gateways',
    category: 'VPC Network',
    worksheetName: 'vDirectLinkGateways',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'type', header: 'Type', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'speedMbps', header: 'Speed (Mbps)', dataType: 'number', defaultVisible: true, sortable: true },
      { field: 'locationName', header: 'Location', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'bgpStatus', header: 'BGP Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'operationalStatus', header: 'Operational Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'global', header: 'Global', dataType: 'boolean', defaultVisible: true, sortable: true },
      { field: 'resourceGroup', header: 'Resource Group', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'directLinkVirtualConnections',
    label: 'Direct Link Virtual Connections',
    category: 'VPC Network',
    worksheetName: 'vDLVirtualConns',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'status', header: 'Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'type', header: 'Type', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'gatewayName', header: 'Gateway', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'networkId', header: 'Network ID', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'networkAccountId', header: 'Network Account', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'vpnGatewayConnections',
    label: 'VPN Gateway Connections',
    category: 'VPC Network',
    worksheetName: 'vVpnGwConns',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'status', header: 'Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'mode', header: 'Mode', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'vpnGatewayName', header: 'VPN Gateway', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'peerAddress', header: 'Peer Address', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'localCidrs', header: 'Local CIDRs', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'peerCidrs', header: 'Peer CIDRs', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'vpcEndpointGateways',
    label: 'Endpoint Gateways',
    category: 'VPC Network',
    worksheetName: 'vVpcEndpointGateways',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'lifecycleState', header: 'Lifecycle State', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'healthState', header: 'Health State', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'target', header: 'Target', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'vpcName', header: 'VPC', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'vpcRoutingTables',
    label: 'Routing Tables',
    category: 'VPC Network',
    worksheetName: 'vVpcRoutingTables',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'vpcName', header: 'VPC', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'isDefault', header: 'Default', dataType: 'boolean', defaultVisible: true, sortable: true },
      { field: 'lifecycleState', header: 'Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'routeCount', header: 'Routes', dataType: 'number', defaultVisible: true, sortable: true },
      { field: 'subnets', header: 'Subnets', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'vpcRoutes',
    label: 'Routes',
    category: 'VPC Network',
    worksheetName: 'vVpcRoutes',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'routingTableName', header: 'Routing Table', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'vpcName', header: 'VPC', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'destination', header: 'Destination CIDR', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'action', header: 'Action', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'nextHopType', header: 'Next Hop Type', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'nextHopTarget', header: 'Next Hop Target', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'zone', header: 'Zone', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'priority', header: 'Priority', dataType: 'number', defaultVisible: false, sortable: true },
      { field: 'origin', header: 'Origin', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },

  // ── Storage ─────────────────────────────────────────────────────
  {
    key: 'vpcVolumes',
    label: 'Block Storage Volumes',
    category: 'VPC Storage',
    worksheetName: 'vVpcVolumes',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'status', header: 'Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'capacity', header: 'Capacity (GB)', dataType: 'number', defaultVisible: true, sortable: true },
      { field: 'iops', header: 'IOPS', dataType: 'number', defaultVisible: true, sortable: true },
      { field: 'profile', header: 'Profile', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'encryption', header: 'Encryption', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'zone', header: 'Zone', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },

  // ── Security ────────────────────────────────────────────────────
  {
    key: 'vpcSshKeys',
    label: 'SSH Keys',
    category: 'VPC Security',
    worksheetName: 'vVpcSshKeys',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'type', header: 'Type', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'fingerprint', header: 'Fingerprint', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'length', header: 'Length', dataType: 'number', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
  {
    key: 'vpcImages',
    label: 'Images (Private)',
    category: 'VPC Security',
    worksheetName: 'vVpcImages',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'status', header: 'Status', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'os', header: 'OS', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'architecture', header: 'Architecture', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },

  // ── Other ───────────────────────────────────────────────────────
  {
    key: 'vpcFlowLogCollectors',
    label: 'Flow Log Collectors',
    category: 'VPC Other',
    worksheetName: 'vVpcFlowLogs',
    columns: [
      { field: 'id', header: 'ID', dataType: 'string', defaultVisible: false, sortable: true },
      { field: 'name', header: 'Name', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'active', header: 'Active', dataType: 'boolean', defaultVisible: true, sortable: true },
      { field: 'lifecycleState', header: 'Lifecycle State', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'target', header: 'Target', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'storageBucket', header: 'Storage Bucket', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'region', header: 'Region', dataType: 'string', defaultVisible: true, sortable: true },
      { field: 'created_at', header: 'Created', dataType: 'date', defaultVisible: false, sortable: true },
    ],
  },
];

export const VPC_CATEGORIES: VpcResourceCategory[] = [
  'VPC Compute',
  'VPC Network',
  'VPC Storage',
  'VPC Security',
  'VPC Other',
];

export function getVpcResourceType(key: string): VpcResourceType | undefined {
  return VPC_RESOURCE_TYPES.find((rt) => rt.key === key);
}

export function getVpcResourcesByCategory(category: VpcResourceCategory): VpcResourceType[] {
  return VPC_RESOURCE_TYPES.filter((rt) => rt.category === category);
}
