import React from 'react';
import { Button, Loading } from '@carbon/react';
import { MachineLearning } from '@carbon/icons-react';
import { useAI } from '@/contexts/AIContext';
import type { MigrationAnalysisOutput } from '@/types/migration';
import '@/styles/ai-common.scss';

interface Props {
  analysisResult: MigrationAnalysisOutput;
}

const AIInsightsPanel: React.FC<Props> = ({ analysisResult }) => {
  const { insights, insightsLoading, insightsError, generateInsights, isAvailable, isConfigured } = useAI();

  if (!isConfigured) return null;

  return (
    <div className="ai-insights-panel">
      <div className="ai-insights-panel__header">
        <h4 className="ai-insights-panel__title">AI Insights</h4>
        <Button
          kind="tertiary"
          size="sm"
          renderIcon={insightsLoading ? undefined : MachineLearning}
          onClick={() => generateInsights(analysisResult)}
          disabled={insightsLoading || !isAvailable}
        >
          {insightsLoading ? (
            <span style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <Loading withOverlay={false} small />
              Generating...
            </span>
          ) : insights ? (
            'Regenerate Insights'
          ) : (
            'Generate AI Insights'
          )}
        </Button>
      </div>

      {!isAvailable && (
        <p style={{ fontSize: '0.8125rem', color: 'var(--cds-text-helper)' }}>
          AI proxy is not connected. Configure it in Settings to enable AI-powered insights.
        </p>
      )}

      {insightsError && (
        <p style={{ fontSize: '0.8125rem', color: 'var(--cds-support-error)' }}>
          {insightsError}
        </p>
      )}

      {insights && (
        <>
          <div className="ai-section__disclaimer">
            Generated by AI (IBM watsonx.ai) — review for accuracy.
          </div>

          <div className="ai-insights-panel__summary">
            <p>{insights.executiveSummary}</p>
          </div>

          {insights.risks.length > 0 && (
            <>
              <h5 style={{ fontSize: '0.875rem', fontWeight: 600, margin: '1rem 0 0.5rem' }}>Key Risks</h5>
              <div className="ai-insights-panel__risks">
                {insights.risks.map((risk, i) => (
                  <div key={i} className="ai-insights-panel__risk-card">
                    <span className={`ai-insights-panel__severity ai-insights-panel__severity--${risk.severity}`}>
                      {risk.severity}
                    </span>
                    <h5>{risk.title}</h5>
                    <p>{risk.description}</p>
                  </div>
                ))}
              </div>
            </>
          )}

          {insights.recommendations.length > 0 && (
            <div className="ai-insights-panel__recommendations">
              <h5>Recommendations</h5>
              <ul>
                {insights.recommendations.map((rec, i) => (
                  <li key={i}>{rec}</li>
                ))}
              </ul>
            </div>
          )}
        </>
      )}
    </div>
  );
};

export default AIInsightsPanel;
