import React from 'react';
import { Button, Loading } from '@carbon/react';
import { MachineLearning } from '@carbon/icons-react';
import { useAI } from '@/contexts/AIContext';
import type { CostAnalysis } from '@/types/migration';
import '@/styles/ai-common.scss';

interface Props {
  costData: CostAnalysis;
}

const AICostInsights: React.FC<Props> = ({ costData }) => {
  const { costOptimization, costLoading, costError, generateCostOptimization, isAvailable, isConfigured } = useAI();

  if (!isConfigured) return null;

  return (
    <div className="ai-cost-insights">
      <div className="ai-cost-insights__header">
        <h4 style={{ margin: 0, fontSize: '1rem', fontWeight: 600 }}>AI Cost Optimization</h4>
        <Button
          kind="tertiary"
          size="sm"
          renderIcon={costLoading ? undefined : MachineLearning}
          onClick={() => generateCostOptimization(costData)}
          disabled={costLoading || !isAvailable}
        >
          {costLoading ? (
            <span style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <Loading withOverlay={false} small />
              Analyzing...
            </span>
          ) : costOptimization ? (
            'Refresh Analysis'
          ) : (
            'AI Suggestions'
          )}
        </Button>
      </div>

      {!isAvailable && (
        <p style={{ fontSize: '0.8125rem', color: 'var(--cds-text-helper)' }}>
          Configure AI proxy in Settings to enable cost optimization suggestions.
        </p>
      )}

      {costError && (
        <p style={{ fontSize: '0.8125rem', color: 'var(--cds-support-error)' }}>
          {costError}
        </p>
      )}

      {costOptimization && (
        <>
          <div className="ai-section__disclaimer">
            Generated by AI (IBM watsonx.ai) — review for accuracy.
          </div>

          <div className="ai-cost-insights__narrative">
            {costOptimization.narrative}
          </div>

          {costOptimization.savings.length > 0 && (
            <div className="ai-cost-insights__savings">
              {costOptimization.savings.map((saving, i) => (
                <div key={i} className="ai-cost-insights__saving-card">
                  <h5>{saving.area}</h5>
                  <p>{saving.description}</p>
                  <span className="estimated-saving">{saving.estimatedSaving}</span>
                </div>
              ))}
            </div>
          )}
        </>
      )}
    </div>
  );
};

export default AICostInsights;
