import { Paragraph, HeadingLevel } from 'docx';
import { heading, body, bullet, spacer, pageBreak } from '../utils/styles';

export function buildAppendices(): Paragraph[] {
  return [
    pageBreak(),
    heading('Appendices'),
    spacer(),

    heading('Glossary', HeadingLevel.HEADING_2),
    bullet('Classic Infrastructure: IBM Cloud Classic (SoftLayer) IaaS platform.'),
    bullet('VPC: IBM Cloud Virtual Private Cloud, the next-generation IaaS platform.'),
    bullet('VSI: Virtual Server Instance.'),
    bullet('VLAN: Virtual Local Area Network.'),
    bullet('CIDR: Classless Inter-Domain Routing, notation for IP address ranges.'),
    bullet('IOPS: Input/Output Operations Per Second.'),
    bullet('TGW: Transit Gateway, for interconnecting VPCs and Classic networks.'),
    bullet('ACL: Access Control List, for subnet-level network traffic filtering.'),
    bullet('LB: Load Balancer, for distributing traffic across multiple servers.'),
    bullet('VPN: Virtual Private Network, for secure site-to-site connectivity.'),
    bullet(
      'Migration Wave: A group of resources migrated together in a coordinated effort.',
    ),
    bullet('Feature Gap: A Classic capability with limited or no VPC equivalent.'),
    spacer(),

    heading('Report Version', HeadingLevel.HEADING_2),
    body('Report generated by IBM Cloud Infrastructure Explorer.'),
    body(`Generation date: ${new Date().toISOString()}`),
    body('Report format version: 2.0 (modular DOCX)'),
    spacer(),
  ];
}
